### ISSUE TITLE
Native WebXR API is enabled on Windows Chrome 78 if webxr-polyfill is loaded

### ISSUE THREAD

**Issue by takahirox** [immersive-web/webxr-polyfill#109]
Probably it isn't a polyfill side problem but a browser side problem, but let me report a weird problem here so far.

Native WebXR API implemented by the browser seems being enabled on Windows Chrome 78 if webxr-polyfill is loaded even though WebXR API is disabled via chrome://flags.

**How to reproduce**

1. Confirm WebXR API is disabled via chrome://flags
2. Go to WebXR samples https://immersive-web.github.io/webxr-samples/immersive-vr-session.html
3. Open web console
4. Type XR, XRSession, or other XR*. You see "f XR() { [native code] }" which means they're declared inside of browser, not polyfill.

```javascript
XR
-> ƒ XR() { [native code] }
XRSession
-> ƒ XRSession() { [native code] }
```

Update: Some other objects seem to be declared by polyfill, not browser.

```javascript
XRWebGLLayer
-> ƒ (session, gl, options) {
        if (!options) {
          options = {};
        }
        options.compositionDisabled = (session._session_mode === "inline");
        return new originalXRLayer(sessi…

navigator.xr
-> XR$1 {Symbol(@@webxr-polyfill/EventTarget): {…}, Symbol(@@webxr-polyfill/XR): {…}, requestSession: ƒ}
```

**Platform I tested on**
- Windows 10
- Version 78.0.3904.87 (Official Build) (64-bit)
- All flags are default on chrome://flags (= WebXR API is disabled)

**Comment by jsantell** [comment]
I've noticed this in the past if "Experimental Web Platform Features" was enabled in `chrome://flags`, even with WebXR disabled.

**Comment by jsantell** [comment]
`XRWebGLLayer` will also always be clobbered by the polyfill to fix Chrome 76-77 composite flag https://github.com/immersive-web/webxr-polyfill/blob/0fad13ef90060863f2a4ba66e969f4cff650797f/src/WebXRPolyfill.js#L163

**Comment by takahirox** [comment]
Thanks for the comment.

> All flags are default on chrome://flags (= WebXR API is disabled)

All flags are default so experimental features is disabled. And on other pages which don't importing  XR* classes are undefined. Only on pages importing webxr-polyfill somehow native WebXR API seems being enabled.

Can you reproduce this issue in your side?

**Comment by takahirox** [comment]
Ah, realized it's because of origin-trial. Sorry for confusing!
