### ISSUE TITLE
Stop re-using the same XRFrame for all events and animation frames

### ISSUE THREAD

**Issue by toji** [immersive-web/webxr-polyfill#114]
As was pointed out in https://github.com/immersive-web/webxr/issues/905 the polyfill is currently re-using the same XRFrame for all animation callbacks and input events that are fired. While more efficient this is not compatible with the spec, and may cause content incompatibilities with native implementations.

**Comment by lojjic** [comment]
I happened across this issue while investigating the problem in issue #115 -- it may make sense for me to go ahead and fix this one in the same PR.

**Comment by lojjic** [comment]
See PR #116 which includes this fix

**Comment by lojjic** [comment]
Fixed by PR #116 - but I don't have permissions to close this issue it seems.

**Comment by toji** [comment]
Thanks for pointing that out! Closing.
