### ISSUE TITLE
Bump version and publish to NPM

### ISSUE THREAD

**Issue by lojjic** [immersive-web/webxr-polyfill#120]
The 1.0.13 version currently [published to NPM](https://www.npmjs.com/package/webxr-polyfill) is extremely out of date, predating all the WebXR 2019 work (#71). This is confusing for folks expecting to import the polyfill via NPM, as the README still gives instructions for doing that. It would be great to bump the version (major version?) and publish it there.

This would probably also cover the CDN request in #62 via cdn.jsdelivr.net or similar.

**Comment by toji** [comment]
Version bumped to 2.0.0 to signal the new API compatibility, and I just published now! 🎉
