### ISSUE TITLE
Android Firefox 68.5.0 is not treated as mobile device

### ISSUE THREAD

**Issue by WoodNeck** [immersive-web/webxr-polyfill#139]
Hello!

Like I've mentioned in the title, Android's Firefox mobile is not treated as a mobile device in this polyfill, which results in "The required feature 'local' is not supported" error.

I've tested it on my device's Firefox browser (Razer phone 2 / Firefox android  68.5.0)
![image](https://user-images.githubusercontent.com/26213435/74329170-9d8dac80-4dd2-11ea-967c-ddeca365f2b3.png)

`isMobile` is grabbed from "utils.js" at [the current master branch](https://github.com/immersive-web/cardboard-vr-display/tree/1c4a79672e9ecf2f7fec80cd1379d2375c3a9e1b)

userAgent is "Mozilla/5.0 (Android 9; Tablet; rv:68.0) Gecko/68.0 Firefox/68.0"

note: I've used polyfill from the CDN(https://cdn.jsdelivr.net/npm/webxr-polyfill@2.0.1/build/webxr-polyfill.min.js)

Thanks.

**Comment by jsantell** [comment]
The polyfills work on Firefox 68 for me on Android AFAICT...

Rewriting the function to take the UA directly, my UA seems to pass the test:

```js
unction isMobile(ua) {
  var check = false;
  (function(a){if(/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows ce|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test(a.substr(0,4)))check = true})(ua);
  return check;
};
```

![Screenshot from 2020-02-12 08-45-34](https://user-images.githubusercontent.com/641267/74357037-24f80300-4d74-11ea-8a6f-75aa0665d119.png)

It looks as if `Tablet` in the UA is breaking that. Is there a reason the Razer 2 would be considered a tablet? (Is it a tablet?)

There's actually another `isMobile` function in [the webxr-polyfill src/utils](https://github.com/immersive-web/webxr-polyfill/blob/d9b595af2bf85763328b159c42ed9cbd90f07b16/src/utils.js) which looks like the same function; should probably reuse the same function so we don't have duplicate functions here.

**Comment by WoodNeck** [comment]
Hey, thanks for the quick response.

Well, that's very odd. Looks like there's something wrong with my phone's userAgent setting, I didn't enabled desktop mode or changed any settings though.
I guess this could be just my phone's problem, as it's quite minor device.
Thanks for the reply :)

**Comment by jsantell** [comment]
No worries, I think a user agent switcher addon should correct this pretty easily FWIW!
