### ISSUE TITLE
IOS 13 rendering upside down with orientation working

### ISSUE THREAD

**Issue by danrossi** [immersive-web/webxr-polyfill#141]
With a user click orientation permission hack. When launching a session, rendering is upside down ?  There is no real world working example to use so I tried my best to make one. 

Click the container to allow orientation then launch. 

I have to debug a work around for now. 

https://dev.electroteque.org/webxr/index2.html

**Comment by danrossi** [comment]
The IOS device check needs fixing up. I also had to do the same. They stitched everyone up there it seems. IOS 13 supports fullscreen so the fullscreen wrapper needs to return. So needs two checks.  for IOS and then another check for fullscreen support ??

```
var isIOS = function () {
  var isIOS = ((/iP(hone|ad)/i).test(navigator.platform) || (navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1));

  return function () {
    return isIOS;
  };
}();
```

**Comment by danrossi** [comment]
It's in the cardboard display project. I might have to fork that to make the edits. I already had to make one to return the canvas back to its original position and not append in the body.

**Comment by jsantell** [comment]
What is the expected behavior on an iPad with fullscreen, stereoscopic rendering? There are no cardboard devices to fit anything of that size, for example.

**Comment by danrossi** [comment]
I don't know. I got a load of complaints it's broken.  It was working previous. There is alot of IOS 13 requests. Android doesn't even use the polyfill so not related.

I've added those fixes into my fork. https://github.com/danrossi/cardboard-vr-display
