### ISSUE TITLE
WebGL2RenderingContext extension breaks polyfill on iOS

### ISSUE THREAD

**Issue by TrevorFSmith** [immersive-web/webxr-polyfill#32]
@jsantell @Squareys 
The recent [addition of WebGL2RenderingContext](https://github.com/immersive-web/webxr-polyfill/commit/5a80cc2eaa7d4d37c87870d5b4c70ae584e1f6d8#diff-77aa3e32292bfe0d6f2e6e669014225eR37) to the required partials on the WebXRPolyfill global value breaks our usage of the polyfill in the WebXR Viewer on iOS, since the WKWebView doesn't offer that class.

One fix would be to remove WebGL2RenderingContext as a requirement and then testing for its existence in the [code that uses it](https://github.com/immersive-web/webxr-polyfill/commit/5a80cc2eaa7d4d37c87870d5b4c70ae584e1f6d8#diff-77aa3e32292bfe0d6f2e6e669014225eR88) but I wanted to check with you two before submitting a PR to make sure that this won't break anything else.

**Comment by jsantell** [comment]
:+1: on WebGL2RenderingContext not being necessary, but polyfilling if it is available

**Comment by TrevorFSmith** [comment]
Ok, I'm testing a fix now and will submit a PR.

**Comment by TrevorFSmith** [comment]
Fixed by #33
