### ISSUE TITLE
No DPDB device match

### ISSUE THREAD

**Issue by soadzoor** [immersive-web/webxr-polyfill#36]
Hi,

I'm trying to get this polyfill work with my OnePlus 3 (Android 8.0) device. Unfortunately, I get the `No DPDB device match` warning, and it doesn't work. If I switch the WebXR flag to enabled in chrome, then my app works, so I guess it should work with the flag disabled with this polyfill. So, what should I do? 

Thanks

**Comment by jsantell** [comment]
It's possible for a device to not have a match and attempts a default Android size. What doesn't work? Is an XRDevice not found? Do you have a test page?

You can also find how to [calculate a DPDB entry here](https://github.com/immersive-web/webvr-polyfill-dpdb), which can be subsequently added to future builds

**Comment by soadzoor** [comment]
Hi, thanks for the quick response. I upgraded the three.js lib to the latest release, and it seems to have solved most of the issue. Still have some warning and errors in the console though:
![capture](https://user-images.githubusercontent.com/10392261/45310654-2857e100-b527-11e8-8f34-5a34e22b6b4b.PNG)


Should I be worried about these?

**Comment by soadzoor** [comment]
I see, thanks!
