### ISSUE TITLE
session immersive not supported in oculus browser

### ISSUE THREAD

**Issue by jfcampos** [immersive-web/webxr-polyfill#38]
It seems that session type "immersive" instead of "exclusive" is not supported yet in oculus browser (Oculus Go). Is it possible to support both terms until the transition is done in all browsers?

This works:
```
navigator.xr.requestDevice().then((device) => {
            device.supportsSession({exclusive: true}).then(() => {
                console.log("Supported");
            });
        });
```

**Comment by jsantell** [comment]
The [shim](https://github.com/immersive-web/webxr-samples/blob/master/js/webxr-version-shim.js) in webxr-samples handles the conversion from non-latest WebXR spec usage to whatever the latest is, e.g. converting `exclusive` to `immersive` on older builds of Chromium, I think this will solve the issue. Is that sufficient?

**Comment by jsantell** [comment]
Also, I did not know that Oculus Go has a WebXR implementation; if so, which Chromium version is it similar to?

**Comment by jfcampos** [comment]
Thanks, that's helpful.

Go uses v61 and does not suppot webxr natively. I was having the non supported error and I didn't know whether or not exclusive/immersive was part of webvr as well. But guess what, it does work now with immersive, I think it was a cache issue...

**Comment by jsantell** [comment]
Sounds good! The spec is going through a lot of changes still so this polyfill will attempt to track the latest, so there will be some growing pains for a bit more.
