### ISSUE TITLE
Change primary button

### ISSUE THREAD

**Issue by jfcampos** [immersive-web/webxr-polyfill#39]
For Mixed Reality through SteamVR, the primary input button for the hand controller is the same button that triggers the SteamVR UI, so you can't really interact with the webxr scene.

Is there a way to change the primaryButtonIndex for an input source (or any other workaround)?

**Comment by jsantell** [comment]
Right now, SteamVR should be picked up as `openvr` IIRC: https://github.com/immersive-web/webxr-polyfill/blob/master/src/devices/WebVRDevice.js#L34-L40

Although that will work for the Vive, not sure about Microsoft MR devices (is that what you're using?)

What's the gamepad.id for the device? Is it similar to the Spatial Controller in [https://github.com/stewdio/THREE.VRController/blob/master/VRController.js#L1116]?

**Comment by jfcampos** [comment]
Yes i'm using MR hand controllers. The id is "Spatial Controller (Spatial Interaction Source) 045E-065B" on edge and "Spatial Controller (Spatial Interaction Source)" on Firefox using SteamVR.

**Comment by jsantell** [comment]
Hmm, then maybe adding `spatial controller` to the map here (with a value of 1) will work? https://github.com/immersive-web/webxr-polyfill/blob/master/src/devices/WebVRDevice.js#L34-L40

Could you try that? I don't have a MR device to test, but I think that would work -- can make the fix if it works for you!

**Comment by jfcampos** [comment]
It works! (PR #40 )

Thanks.

**Comment by jsantell** [comment]
Fixed via #40
