### ISSUE TITLE
Polyfill detected as JS Trojan

### ISSUE THREAD

**Issue by jfcampos** [immersive-web/webxr-polyfill#44]
We had reports of these 2 antivirus:
AVG (Chrome Windows 10)
Avast (Chrome Mac OSX)

Blocking the polyfill from running, flagging it for being infected with _JS:Downloader-EAX Trojan_.

Doing some debug, we found out that the warning comes up while running `Dpdb.prototype.calcDeviceParams_`

**Comment by jfcampos** [comment]
Just confirmed the issue is actually related to the _name_ of the function **Dpdb.prototype.matchRule_**. Just changing it we don't get the alert. I'm submitting this to the cardboard-vr-display repo

**Comment by jfcampos** [comment]
Did a PR 
https://github.com/immersive-web/cardboard-vr-display/pull/32

Can/will do another PR here if it gets merged

**Comment by TrevorFSmith** [comment]
That's a great catch, @jfcampos!

It's sort of alarming that such an innocuous name is flagged but perhaps a bit of malware happened to use the same naming patterns.

**Comment by jsantell** [comment]
Fixed in 1.0.12
