### ISSUE TITLE
[WebXR 2019] XRSpace

### ISSUE THREAD

**Issue by jsantell** [immersive-web/webxr-polyfill#50]
Currently, the old XRCoordinateSystem is implemented, as well as supporting bounded areas at least.

The following classes are new in WebXR 2019:
* XRSpace
* XRReferenceSpace
* XRBoundedReferenceSpace

As well as some API renaming (`session.requestReferenceSpace`).

AFAIK, there are no current coordinate system events, but supporting [XRReferenceSpaceEvent](https://immersive-web.github.io/webxr/#xrreferencespaceevent-interface) is also needed

See https://github.com/immersive-web/webxr-polyfill/issues/51 for more information on this effort, and development goals.

**Comment by jsantell** [comment]
@jacobcdewitt is taking a look at this

**Comment by toji** [comment]
Closed by #71
