### ISSUE TITLE
WebXR 2019

### ISSUE THREAD

**Issue by jsantell** [immersive-web/webxr-polyfill#51]
This is a meta bug for discussion around updating the polyfill to the latest version of the spec now that things have settled down a bit.

I've created a handful of categorized issues, detailing what I'm aware of that has changed at least, and areas that probably need to be confirmed. The issues are all tagged in the [WebXR 2019 milestone](https://github.com/immersive-web/webxr-polyfill/milestone/1).

## Contributing/development

If you're interested in contributing, express interest in an issue! We will be using the [webxr-2019 branch](https://github.com/immersive-web/webxr-polyfill/tree/webxr-2019) for PRs. There are examples (originally from [webxr-samples](https://github.com/immersive-web/webxr-samples/)) in the repo that we can use to test progress as we iterate inbetween two APIs, hopefully ending up with something functionally similar to what could be on webxr samples in the future.

The polyfill has two main areas: the API plumbing ([src/api/*](https://github.com/immersive-web/webxr-polyfill/tree/master/src/api)) and providers ([src/devices/*](https://github.com/immersive-web/webxr-polyfill/tree/master/src/devices). Not only will the API have to be updated to match the spec, but the input between the API and the underlying provider may also need to change.

We can test against WebVR and non-WebVR mobile browsers using the [WebVRDevice provider](https://github.com/immersive-web/webxr-polyfill/blob/master/src/devices/WebVRDevice.js) and [CardboardXRDevice provider](https://github.com/immersive-web/webxr-polyfill/blob/master/src/devices/CardboardXRDevice.js). If we can incrementally make these changes while updating the local examples, then we should still be able to support the examples in these browsers as a means of testing. In addition to the traditional unit tests here to help with the plumbing.

Happy to answer any questions about the structure of the current code!

**Comment by cwilso** [comment]
I added the agenda label because I want to make sure we discuss the polyfill and its trajectory in the next WG call.

**Comment by jsantell** [comment]
The migration to the current WebXR standard has been completed.
