### ISSUE TITLE
[WebXR 2019] XRPose/XRViewerPose

### ISSUE THREAD

**Issue by jsantell** [immersive-web/webxr-polyfill#52]
* XRPose/XRViewerPose need to be implemented, replacing XRDevicePose.
* `frame.getViewerPose()`, `frame.getPose()` need to be implemented on XRFrame
* `pose.emulatedPosition`
* [`XRRigidTransform`](https://immersive-web.github.io/webxr/#xrrigidtransform)

See https://github.com/immersive-web/webxr-polyfill/issues/51 for more information on this effort, and development goals.

**Comment by jsantell** [comment]
@jacobcdewitt is taking a look at this

**Comment by toji** [comment]
Closed by #71
