### ISSUE TITLE
[WebXR 2019] Rendering

### ISSUE THREAD

**Issue by jsantell** [immersive-web/webxr-polyfill#53]
This may need to be broken up into smaller issues.

Currently needing implementation AFAIK:

* `session.renderState`
* `session.updateRenderState`
* `layer.getNativeFramebufferScaleFactor`
* `layer.ignoreDepthValues`
* `getViewport()` moved from XRLayer to XRWebGLLayer
* `gl.makeXRCompatible()` rename
* Any changes to `XRPresentationContext`, in light of the potential inline changes? https://github.com/immersive-web/webxr/issues/636

See https://github.com/immersive-web/webxr-polyfill/issues/51 for more information on this effort, and development goals.

**Comment by toji** [comment]
At least partially fixed by #71. Need to verify that all listed features are covered.

**Comment by jsantell** [comment]
The migration to the current WebXR standard has been completed.
