### ISSUE TITLE
[WebXR 2019] Input

### ISSUE THREAD

**Issue by jsantell** [immersive-web/webxr-polyfill#54]
There doesn't seem to be too much missing from the current input implementation, but this hasn't been tested in awhile. A lot of TBD here. AFAIK things that are new:

* `gripSpace` (dependent on #50 XRSpace)
* Pointer events
* Gamepad integration(?)

See https://github.com/immersive-web/webxr-polyfill/issues/51 for more information on this effort, and development goals.

**Comment by jacobcdewitt** [comment]
We should also add a page in the examples folder to test this.

**Comment by toji** [comment]
Closed by #71
