### ISSUE TITLE
Please make it clear that WebXR is not finished

### ISSUE THREAD

**Issue by blairmacintyre** [immersive-web/webxr-polyfill#6]
The README for the polyfill is presenting this as "an implementation of WebXR".

But WebXR is not finished, and will be continuing to change for a little while. 

Please add a banner to the top of the README saying that this will track WebXR as it is being defined, and that it will change without notice.

We don't want people writing code assuming this is the final standard.

**Comment by jsantell** [comment]
Great call and 100% agree
