### ISSUE TITLE
Merge webxr-2019 branch into master

### ISSUE THREAD

**Issue by toji** [immersive-web/webxr-polyfill#75]
@jsantell: While it's not 100% complete the code in the `webxr-2019` branch is relatively functional and can run a majority of the code written against the current WebXR spec, the VR portion of which we no longer expect to break backwards compatibility with.

Given that the master branch now reflects a version of the spec that will never be shipped, it's currently pretty awkward to tell people how to get to the polyfill for testing. As such I think it would be appropriate to merge the `webxr-2019` branch into master relatively soon, and continue development there. What, if anything, would you like to see happen prior to that merge?

**Comment by joshmarinacci** [comment]
I think you've hit the limit of what can be fixed before merging back to master.  Merge it in and lets just start using it for everything and see what breaks!

**Comment by jsantell** [comment]
If it's working with most of the examples, that sounds great; let's get it merged, and start filing issues we find -- tests are probably the biggest one!

**Comment by toji** [comment]
Poof! Done!
