### ISSUE TITLE
XRFrame.getViewerPose() always returns the same XRViewerPose instance

### ISSUE THREAD

**Issue by takahirox** [immersive-web/webxr-polyfill#97]
`.getViewerPose()` of a `XRFrame` instance always returns the same `XRViewerPose` instance.

```javascript
getViewerPose(space) {
  this[PRIVATE].viewerPose._updateFromReferenceSpace(space);
  return this[PRIVATE].viewerPose;
}
```

https://github.com/immersive-web/webxr-polyfill/blob/master/src/api/XRFrame.js#L55-L58

So if I get two or more viewer poses of difference reference spaces in an animation frame, the returned viewer poses instances are identical and overridden by the last `.getViewerPose()` call.

```javascript
const viewerSpaceViewerPose = frame.getViewrPose(viewerReferenceSpace);
const localSpaceViewerPose = frame.getViewerPose(localReferenceSpace);
// viewerSpaceViewerPose === localSpaceViewerPose is true
```

Is this design intentional? (Sorry if I'm missing something in the spec.)

If not I think `.getViewerPose()` should create a new `XRViewerPose` instance for each call.

**Comment by lojjic** [comment]
Looks like PR #122 takes care of this.

**Comment by toji** [comment]
Yes, it will.

**Comment by takahirox** [comment]
Closing in favor of #122, thanks!
